# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 13:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='blockers',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
