# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_auto_20160117_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
