---
# vim:sw=2:ft=ansible

django_enabled: yes                           # The role is enabled

django_manage_list:                           # List of commands which will be executed
  - collectstatic
  - syncdb
  - migrate

django_src_dir: "{{wsgi_src_dir}}"           # Path to django application
django_etc_dir: "{{wsgi_etc_dir}}"           # Where place a configuration files
django_env_dir: "{{wsgi_env_dir}}"           # Use virtualenv (set blank "" to disable)

# Generate local settings
django_settings_imports:
  - from .{{deploy_env}} import *
django_settings_module: main.settings.local
django_settings_dir: "{{django_src_dir}}/{{django_settings_module.split('.')[:-1]|join('/')}}"
django_settings: "{{django_src_dir}}/{{django_settings_module.replace('.', '/')}}.py"
django_settings_additional: []                # List of strings to add Django settings
                                              # Ex. django_settings_additional:
                                              #       - DEBUG = True
                                              #       - URLCONF = 'urls'
django_settings_databases: []                 # List of databases to add Django settings
                                              # Ex. django_settings_databases:
                                              #       - default:
                                              #           NAME: test
                                              #           USER: test
                                              #           PASSWORD: test
django_settings_caches: []                    # List of cache backends to add Django settings
                                              # Ex. django_settings_caches:
                                              #       - default:
                                              #           BACKEND: django.core.cache.backends.locmem.LocMemCache
                                              #           KEY_PREFIX: my_own_prefix
